CC = g++
FLAGS = -g -Wall -ansi


AB_DIR = ../lib
LIB = -lrt -lpthread -ldl


OBJ_DIR = ./bin
SRC = $(wildcard *.cpp)
#OBJ = $(patsubst %.cpp,$(OBJ_DIR)/%.o,$(SRC))
header=$(shell find ./ -iname "*.h" )

all: jrtf
	@echo Chen Ming

print:
	@echo Chen Ming

jrtf:
	@echo Chen Ming1111
	$(CC) -c $(SRC) $(LIB)
	#$(OBJ)
	#%.o: %.cpp $(header)
		#$(CC) $(FLAGS) -c $< -o $@
	#$(CC) -O $(OBJ_DIR)/$@ $(OBJ)
 